/* This file was generated by SableCC (http://www.sablecc.org/). */

package linguagem.analysis;

import linguagem.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTId(TId node);
    void caseTReal(TReal node);
    void caseTInteiro(TInteiro node);
    void caseTString(TString node);
    void caseTBooleano(TBooleano node);
    void caseTSe(TSe node);
    void caseTSenao(TSenao node);
    void caseTEnquanto(TEnquanto node);
    void caseTPara(TPara node);
    void caseTCaso(TCaso node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBlocoAbre(TComentarioBlocoAbre node);
    void caseTComentarioBlocoFecha(TComentarioBlocoFecha node);
    void caseTSoma(TSoma node);
    void caseTSub(TSub node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMaior(TMaior node);
    void caseTMenor(TMenor node);
    void caseTIgual(TIgual node);
    void caseTMaiorIgual(TMaiorIgual node);
    void caseTMenorIgual(TMenorIgual node);
    void caseTDiferente(TDiferente node);
    void caseTInicioBloco(TInicioBloco node);
    void caseTFimBloco(TFimBloco node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTAbreParentesis(TAbreParentesis node);
    void caseTFechaParentesis(TFechaParentesis node);
    void caseTAbreColchetes(TAbreColchetes node);
    void caseTFechaColchetes(TFechaColchetes node);
    void caseTPonto(TPonto node);
    void caseTVirgula(TVirgula node);
    void caseTPontoEVirgula(TPontoEVirgula node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTAspasSimples(TAspasSimples node);
    void caseTAspasDuplas(TAspasDuplas node);
    void caseTNovaLinha(TNovaLinha node);
    void caseTEspaco(TEspaco node);
    void caseTTab(TTab node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
