/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AAlgoCommLeia extends PCommLeia
{
    private PVar _var_;
    private PCommLeia _commLeia_;

    public AAlgoCommLeia()
    {
        // Constructor
    }

    public AAlgoCommLeia(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") PCommLeia _commLeia_)
    {
        // Constructor
        setVar(_var_);

        setCommLeia(_commLeia_);

    }

    @Override
    public Object clone()
    {
        return new AAlgoCommLeia(
            cloneNode(this._var_),
            cloneNode(this._commLeia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlgoCommLeia(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PCommLeia getCommLeia()
    {
        return this._commLeia_;
    }

    public void setCommLeia(PCommLeia node)
    {
        if(this._commLeia_ != null)
        {
            this._commLeia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commLeia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._commLeia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._commLeia_ == child)
        {
            this._commLeia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._commLeia_ == oldChild)
        {
            setCommLeia((PCommLeia) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
