/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AAritMultAritSub extends PAritSub
{
    private PAritMult _aritMult_;

    public AAritMultAritSub()
    {
        // Constructor
    }

    public AAritMultAritSub(
        @SuppressWarnings("hiding") PAritMult _aritMult_)
    {
        // Constructor
        setAritMult(_aritMult_);

    }

    @Override
    public Object clone()
    {
        return new AAritMultAritSub(
            cloneNode(this._aritMult_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAritMultAritSub(this);
    }

    public PAritMult getAritMult()
    {
        return this._aritMult_;
    }

    public void setAritMult(PAritMult node)
    {
        if(this._aritMult_ != null)
        {
            this._aritMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aritMult_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aritMult_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aritMult_ == child)
        {
            this._aritMult_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aritMult_ == oldChild)
        {
            setAritMult((PAritMult) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
