/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AAritSubAritSoma extends PAritSoma
{
    private PAritSub _aritSub_;

    public AAritSubAritSoma()
    {
        // Constructor
    }

    public AAritSubAritSoma(
        @SuppressWarnings("hiding") PAritSub _aritSub_)
    {
        // Constructor
        setAritSub(_aritSub_);

    }

    @Override
    public Object clone()
    {
        return new AAritSubAritSoma(
            cloneNode(this._aritSub_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAritSubAritSoma(this);
    }

    public PAritSub getAritSub()
    {
        return this._aritSub_;
    }

    public void setAritSub(PAritSub node)
    {
        if(this._aritSub_ != null)
        {
            this._aritSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aritSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aritSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aritSub_ == child)
        {
            this._aritSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aritSub_ == oldChild)
        {
            setAritSub((PAritSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
