/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AAvalieSimplesAvalieSenao extends PAvalieSenao
{
    private PPosAvalie _posAvalie_;

    public AAvalieSimplesAvalieSenao()
    {
        // Constructor
    }

    public AAvalieSimplesAvalieSenao(
        @SuppressWarnings("hiding") PPosAvalie _posAvalie_)
    {
        // Constructor
        setPosAvalie(_posAvalie_);

    }

    @Override
    public Object clone()
    {
        return new AAvalieSimplesAvalieSenao(
            cloneNode(this._posAvalie_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvalieSimplesAvalieSenao(this);
    }

    public PPosAvalie getPosAvalie()
    {
        return this._posAvalie_;
    }

    public void setPosAvalie(PPosAvalie node)
    {
        if(this._posAvalie_ != null)
        {
            this._posAvalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._posAvalie_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._posAvalie_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._posAvalie_ == child)
        {
            this._posAvalie_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._posAvalie_ == oldChild)
        {
            setPosAvalie((PPosAvalie) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
