/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AComandoEnquantoComm extends PComm
{
    private TEnquanto _enquanto_;
    private TAbreParentesis _abreParentesis_;
    private PExpLogicaInicial _expLogicaInicial_;
    private TFechaParentesis _fechaParentesis_;
    private TFaca _faca_;
    private PMultiplosComm _multiplosComm_;
    private PFimEnquanto _fimEnquanto_;
    private TPontoVirgula _pontoVirgula_;

    public AComandoEnquantoComm()
    {
        // Constructor
    }

    public AComandoEnquantoComm(
        @SuppressWarnings("hiding") TEnquanto _enquanto_,
        @SuppressWarnings("hiding") TAbreParentesis _abreParentesis_,
        @SuppressWarnings("hiding") PExpLogicaInicial _expLogicaInicial_,
        @SuppressWarnings("hiding") TFechaParentesis _fechaParentesis_,
        @SuppressWarnings("hiding") TFaca _faca_,
        @SuppressWarnings("hiding") PMultiplosComm _multiplosComm_,
        @SuppressWarnings("hiding") PFimEnquanto _fimEnquanto_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setEnquanto(_enquanto_);

        setAbreParentesis(_abreParentesis_);

        setExpLogicaInicial(_expLogicaInicial_);

        setFechaParentesis(_fechaParentesis_);

        setFaca(_faca_);

        setMultiplosComm(_multiplosComm_);

        setFimEnquanto(_fimEnquanto_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AComandoEnquantoComm(
            cloneNode(this._enquanto_),
            cloneNode(this._abreParentesis_),
            cloneNode(this._expLogicaInicial_),
            cloneNode(this._fechaParentesis_),
            cloneNode(this._faca_),
            cloneNode(this._multiplosComm_),
            cloneNode(this._fimEnquanto_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoEnquantoComm(this);
    }

    public TEnquanto getEnquanto()
    {
        return this._enquanto_;
    }

    public void setEnquanto(TEnquanto node)
    {
        if(this._enquanto_ != null)
        {
            this._enquanto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enquanto_ = node;
    }

    public TAbreParentesis getAbreParentesis()
    {
        return this._abreParentesis_;
    }

    public void setAbreParentesis(TAbreParentesis node)
    {
        if(this._abreParentesis_ != null)
        {
            this._abreParentesis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParentesis_ = node;
    }

    public PExpLogicaInicial getExpLogicaInicial()
    {
        return this._expLogicaInicial_;
    }

    public void setExpLogicaInicial(PExpLogicaInicial node)
    {
        if(this._expLogicaInicial_ != null)
        {
            this._expLogicaInicial_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaInicial_ = node;
    }

    public TFechaParentesis getFechaParentesis()
    {
        return this._fechaParentesis_;
    }

    public void setFechaParentesis(TFechaParentesis node)
    {
        if(this._fechaParentesis_ != null)
        {
            this._fechaParentesis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParentesis_ = node;
    }

    public TFaca getFaca()
    {
        return this._faca_;
    }

    public void setFaca(TFaca node)
    {
        if(this._faca_ != null)
        {
            this._faca_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._faca_ = node;
    }

    public PMultiplosComm getMultiplosComm()
    {
        return this._multiplosComm_;
    }

    public void setMultiplosComm(PMultiplosComm node)
    {
        if(this._multiplosComm_ != null)
        {
            this._multiplosComm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplosComm_ = node;
    }

    public PFimEnquanto getFimEnquanto()
    {
        return this._fimEnquanto_;
    }

    public void setFimEnquanto(PFimEnquanto node)
    {
        if(this._fimEnquanto_ != null)
        {
            this._fimEnquanto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimEnquanto_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enquanto_)
            + toString(this._abreParentesis_)
            + toString(this._expLogicaInicial_)
            + toString(this._fechaParentesis_)
            + toString(this._faca_)
            + toString(this._multiplosComm_)
            + toString(this._fimEnquanto_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enquanto_ == child)
        {
            this._enquanto_ = null;
            return;
        }

        if(this._abreParentesis_ == child)
        {
            this._abreParentesis_ = null;
            return;
        }

        if(this._expLogicaInicial_ == child)
        {
            this._expLogicaInicial_ = null;
            return;
        }

        if(this._fechaParentesis_ == child)
        {
            this._fechaParentesis_ = null;
            return;
        }

        if(this._faca_ == child)
        {
            this._faca_ = null;
            return;
        }

        if(this._multiplosComm_ == child)
        {
            this._multiplosComm_ = null;
            return;
        }

        if(this._fimEnquanto_ == child)
        {
            this._fimEnquanto_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enquanto_ == oldChild)
        {
            setEnquanto((TEnquanto) newChild);
            return;
        }

        if(this._abreParentesis_ == oldChild)
        {
            setAbreParentesis((TAbreParentesis) newChild);
            return;
        }

        if(this._expLogicaInicial_ == oldChild)
        {
            setExpLogicaInicial((PExpLogicaInicial) newChild);
            return;
        }

        if(this._fechaParentesis_ == oldChild)
        {
            setFechaParentesis((TFechaParentesis) newChild);
            return;
        }

        if(this._faca_ == oldChild)
        {
            setFaca((TFaca) newChild);
            return;
        }

        if(this._multiplosComm_ == oldChild)
        {
            setMultiplosComm((PMultiplosComm) newChild);
            return;
        }

        if(this._fimEnquanto_ == oldChild)
        {
            setFimEnquanto((PFimEnquanto) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
