/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class ACommRepitaCommsParte extends PCommRepitaCommsParte
{
    private PComms _comms_;
    private PCommRepitaCondicaoParte _commRepitaCondicaoParte_;

    public ACommRepitaCommsParte()
    {
        // Constructor
    }

    public ACommRepitaCommsParte(
        @SuppressWarnings("hiding") PComms _comms_,
        @SuppressWarnings("hiding") PCommRepitaCondicaoParte _commRepitaCondicaoParte_)
    {
        // Constructor
        setComms(_comms_);

        setCommRepitaCondicaoParte(_commRepitaCondicaoParte_);

    }

    @Override
    public Object clone()
    {
        return new ACommRepitaCommsParte(
            cloneNode(this._comms_),
            cloneNode(this._commRepitaCondicaoParte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommRepitaCommsParte(this);
    }

    public PComms getComms()
    {
        return this._comms_;
    }

    public void setComms(PComms node)
    {
        if(this._comms_ != null)
        {
            this._comms_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comms_ = node;
    }

    public PCommRepitaCondicaoParte getCommRepitaCondicaoParte()
    {
        return this._commRepitaCondicaoParte_;
    }

    public void setCommRepitaCondicaoParte(PCommRepitaCondicaoParte node)
    {
        if(this._commRepitaCondicaoParte_ != null)
        {
            this._commRepitaCondicaoParte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commRepitaCondicaoParte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comms_)
            + toString(this._commRepitaCondicaoParte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comms_ == child)
        {
            this._comms_ = null;
            return;
        }

        if(this._commRepitaCondicaoParte_ == child)
        {
            this._commRepitaCondicaoParte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comms_ == oldChild)
        {
            setComms((PComms) newChild);
            return;
        }

        if(this._commRepitaCondicaoParte_ == oldChild)
        {
            setCommRepitaCondicaoParte((PCommRepitaCondicaoParte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
