/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AComSenaoCommSe extends PCommSe
{
    private PExpLogica _expLogica_;
    private PComms _comms_;
    private PCommSeSenao _commSeSenao_;

    public AComSenaoCommSe()
    {
        // Constructor
    }

    public AComSenaoCommSe(
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") PComms _comms_,
        @SuppressWarnings("hiding") PCommSeSenao _commSeSenao_)
    {
        // Constructor
        setExpLogica(_expLogica_);

        setComms(_comms_);

        setCommSeSenao(_commSeSenao_);

    }

    @Override
    public Object clone()
    {
        return new AComSenaoCommSe(
            cloneNode(this._expLogica_),
            cloneNode(this._comms_),
            cloneNode(this._commSeSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComSenaoCommSe(this);
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public PComms getComms()
    {
        return this._comms_;
    }

    public void setComms(PComms node)
    {
        if(this._comms_ != null)
        {
            this._comms_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comms_ = node;
    }

    public PCommSeSenao getCommSeSenao()
    {
        return this._commSeSenao_;
    }

    public void setCommSeSenao(PCommSeSenao node)
    {
        if(this._commSeSenao_ != null)
        {
            this._commSeSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commSeSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_)
            + toString(this._comms_)
            + toString(this._commSeSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._comms_ == child)
        {
            this._comms_ = null;
            return;
        }

        if(this._commSeSenao_ == child)
        {
            this._commSeSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._comms_ == oldChild)
        {
            setComms((PComms) newChild);
            return;
        }

        if(this._commSeSenao_ == oldChild)
        {
            setCommSeSenao((PCommSeSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
