/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class ACommEnquantoFim extends PCommEnquantoFim
{

    public ACommEnquantoFim()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ACommEnquantoFim();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommEnquantoFim(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
