/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AComPassoCommParaPassa extends PCommParaPassa
{
    private TInteiro _inteiro_;
    private PCommParaAte _commParaAte_;

    public AComPassoCommParaPassa()
    {
        // Constructor
    }

    public AComPassoCommParaPassa(
        @SuppressWarnings("hiding") TInteiro _inteiro_,
        @SuppressWarnings("hiding") PCommParaAte _commParaAte_)
    {
        // Constructor
        setInteiro(_inteiro_);

        setCommParaAte(_commParaAte_);

    }

    @Override
    public Object clone()
    {
        return new AComPassoCommParaPassa(
            cloneNode(this._inteiro_),
            cloneNode(this._commParaAte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComPassoCommParaPassa(this);
    }

    public TInteiro getInteiro()
    {
        return this._inteiro_;
    }

    public void setInteiro(TInteiro node)
    {
        if(this._inteiro_ != null)
        {
            this._inteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inteiro_ = node;
    }

    public PCommParaAte getCommParaAte()
    {
        return this._commParaAte_;
    }

    public void setCommParaAte(PCommParaAte node)
    {
        if(this._commParaAte_ != null)
        {
            this._commParaAte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commParaAte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inteiro_)
            + toString(this._commParaAte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inteiro_ == child)
        {
            this._inteiro_ = null;
            return;
        }

        if(this._commParaAte_ == child)
        {
            this._commParaAte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inteiro_ == oldChild)
        {
            setInteiro((TInteiro) newChild);
            return;
        }

        if(this._commParaAte_ == oldChild)
        {
            setCommParaAte((PCommParaAte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
