/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExpMenorIgualExpExplogicaMenorigual extends PExplogicaMenorigual
{
    private PExp _exp_;
    private TMenorIgual _menorIgual_;
    private PExplogicaMaior _explogicaMaior_;

    public AExpMenorIgualExpExplogicaMenorigual()
    {
        // Constructor
    }

    public AExpMenorIgualExpExplogicaMenorigual(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMenorIgual _menorIgual_,
        @SuppressWarnings("hiding") PExplogicaMaior _explogicaMaior_)
    {
        // Constructor
        setExp(_exp_);

        setMenorIgual(_menorIgual_);

        setExplogicaMaior(_explogicaMaior_);

    }

    @Override
    public Object clone()
    {
        return new AExpMenorIgualExpExplogicaMenorigual(
            cloneNode(this._exp_),
            cloneNode(this._menorIgual_),
            cloneNode(this._explogicaMaior_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMenorIgualExpExplogicaMenorigual(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMenorIgual getMenorIgual()
    {
        return this._menorIgual_;
    }

    public void setMenorIgual(TMenorIgual node)
    {
        if(this._menorIgual_ != null)
        {
            this._menorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorIgual_ = node;
    }

    public PExplogicaMaior getExplogicaMaior()
    {
        return this._explogicaMaior_;
    }

    public void setExplogicaMaior(PExplogicaMaior node)
    {
        if(this._explogicaMaior_ != null)
        {
            this._explogicaMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaMaior_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._menorIgual_)
            + toString(this._explogicaMaior_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._menorIgual_ == child)
        {
            this._menorIgual_ = null;
            return;
        }

        if(this._explogicaMaior_ == child)
        {
            this._explogicaMaior_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._menorIgual_ == oldChild)
        {
            setMenorIgual((TMenorIgual) newChild);
            return;
        }

        if(this._explogicaMaior_ == oldChild)
        {
            setExplogicaMaior((PExplogicaMaior) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
