/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExplogicaNotExplogicaMaiorigual extends PExplogicaMaiorigual
{
    private PExplogicaNot _explogicaNot_;

    public AExplogicaNotExplogicaMaiorigual()
    {
        // Constructor
    }

    public AExplogicaNotExplogicaMaiorigual(
        @SuppressWarnings("hiding") PExplogicaNot _explogicaNot_)
    {
        // Constructor
        setExplogicaNot(_explogicaNot_);

    }

    @Override
    public Object clone()
    {
        return new AExplogicaNotExplogicaMaiorigual(
            cloneNode(this._explogicaNot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExplogicaNotExplogicaMaiorigual(this);
    }

    public PExplogicaNot getExplogicaNot()
    {
        return this._explogicaNot_;
    }

    public void setExplogicaNot(PExplogicaNot node)
    {
        if(this._explogicaNot_ != null)
        {
            this._explogicaNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaNot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogicaNot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogicaNot_ == child)
        {
            this._explogicaNot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogicaNot_ == oldChild)
        {
            setExplogicaNot((PExplogicaNot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
