/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExplogicaMenorigualExplogicaMenor extends PExplogicaMenor
{
    private PExplogicaMenorigual _explogicaMenorigual_;

    public AExplogicaMenorigualExplogicaMenor()
    {
        // Constructor
    }

    public AExplogicaMenorigualExplogicaMenor(
        @SuppressWarnings("hiding") PExplogicaMenorigual _explogicaMenorigual_)
    {
        // Constructor
        setExplogicaMenorigual(_explogicaMenorigual_);

    }

    @Override
    public Object clone()
    {
        return new AExplogicaMenorigualExplogicaMenor(
            cloneNode(this._explogicaMenorigual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExplogicaMenorigualExplogicaMenor(this);
    }

    public PExplogicaMenorigual getExplogicaMenorigual()
    {
        return this._explogicaMenorigual_;
    }

    public void setExplogicaMenorigual(PExplogicaMenorigual node)
    {
        if(this._explogicaMenorigual_ != null)
        {
            this._explogicaMenorigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaMenorigual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogicaMenorigual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogicaMenorigual_ == child)
        {
            this._explogicaMenorigual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogicaMenorigual_ == oldChild)
        {
            setExplogicaMenorigual((PExplogicaMenorigual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
