/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExpMenorIgualExpExpLogica extends PExpLogica
{
    private PExp _exp_;
    private TMenorIgual _menorIgual_;
    private PPosExp _posExp_;

    public AExpMenorIgualExpExpLogica()
    {
        // Constructor
    }

    public AExpMenorIgualExpExpLogica(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMenorIgual _menorIgual_,
        @SuppressWarnings("hiding") PPosExp _posExp_)
    {
        // Constructor
        setExp(_exp_);

        setMenorIgual(_menorIgual_);

        setPosExp(_posExp_);

    }

    @Override
    public Object clone()
    {
        return new AExpMenorIgualExpExpLogica(
            cloneNode(this._exp_),
            cloneNode(this._menorIgual_),
            cloneNode(this._posExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMenorIgualExpExpLogica(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMenorIgual getMenorIgual()
    {
        return this._menorIgual_;
    }

    public void setMenorIgual(TMenorIgual node)
    {
        if(this._menorIgual_ != null)
        {
            this._menorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorIgual_ = node;
    }

    public PPosExp getPosExp()
    {
        return this._posExp_;
    }

    public void setPosExp(PPosExp node)
    {
        if(this._posExp_ != null)
        {
            this._posExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._posExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._menorIgual_)
            + toString(this._posExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._menorIgual_ == child)
        {
            this._menorIgual_ = null;
            return;
        }

        if(this._posExp_ == child)
        {
            this._posExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._menorIgual_ == oldChild)
        {
            setMenorIgual((TMenorIgual) newChild);
            return;
        }

        if(this._posExp_ == oldChild)
        {
            setPosExp((PPosExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
