/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExplogicaXorExplogicaExpLogica extends PExpLogica
{
    private PExpLogica _expLogica_;
    private TXor _xor_;
    private PPosExplogica _posExplogica_;

    public AExplogicaXorExplogicaExpLogica()
    {
        // Constructor
    }

    public AExplogicaXorExplogicaExpLogica(
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TXor _xor_,
        @SuppressWarnings("hiding") PPosExplogica _posExplogica_)
    {
        // Constructor
        setExpLogica(_expLogica_);

        setXor(_xor_);

        setPosExplogica(_posExplogica_);

    }

    @Override
    public Object clone()
    {
        return new AExplogicaXorExplogicaExpLogica(
            cloneNode(this._expLogica_),
            cloneNode(this._xor_),
            cloneNode(this._posExplogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExplogicaXorExplogicaExpLogica(this);
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TXor getXor()
    {
        return this._xor_;
    }

    public void setXor(TXor node)
    {
        if(this._xor_ != null)
        {
            this._xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xor_ = node;
    }

    public PPosExplogica getPosExplogica()
    {
        return this._posExplogica_;
    }

    public void setPosExplogica(PPosExplogica node)
    {
        if(this._posExplogica_ != null)
        {
            this._posExplogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._posExplogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_)
            + toString(this._xor_)
            + toString(this._posExplogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._xor_ == child)
        {
            this._xor_ = null;
            return;
        }

        if(this._posExplogica_ == child)
        {
            this._posExplogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(this._posExplogica_ == oldChild)
        {
            setPosExplogica((PPosExplogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
