/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExpMaiorIgualExpExplogicaMaiorigual extends PExplogicaMaiorigual
{
    private PExp _exp_;
    private TMaiorIgual _maiorIgual_;
    private PExplogicaMaiorigual _explogicaMaiorigual_;

    public AExpMaiorIgualExpExplogicaMaiorigual()
    {
        // Constructor
    }

    public AExpMaiorIgualExpExplogicaMaiorigual(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMaiorIgual _maiorIgual_,
        @SuppressWarnings("hiding") PExplogicaMaiorigual _explogicaMaiorigual_)
    {
        // Constructor
        setExp(_exp_);

        setMaiorIgual(_maiorIgual_);

        setExplogicaMaiorigual(_explogicaMaiorigual_);

    }

    @Override
    public Object clone()
    {
        return new AExpMaiorIgualExpExplogicaMaiorigual(
            cloneNode(this._exp_),
            cloneNode(this._maiorIgual_),
            cloneNode(this._explogicaMaiorigual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMaiorIgualExpExplogicaMaiorigual(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMaiorIgual getMaiorIgual()
    {
        return this._maiorIgual_;
    }

    public void setMaiorIgual(TMaiorIgual node)
    {
        if(this._maiorIgual_ != null)
        {
            this._maiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorIgual_ = node;
    }

    public PExplogicaMaiorigual getExplogicaMaiorigual()
    {
        return this._explogicaMaiorigual_;
    }

    public void setExplogicaMaiorigual(PExplogicaMaiorigual node)
    {
        if(this._explogicaMaiorigual_ != null)
        {
            this._explogicaMaiorigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaMaiorigual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._maiorIgual_)
            + toString(this._explogicaMaiorigual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._maiorIgual_ == child)
        {
            this._maiorIgual_ = null;
            return;
        }

        if(this._explogicaMaiorigual_ == child)
        {
            this._explogicaMaiorigual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._maiorIgual_ == oldChild)
        {
            setMaiorIgual((TMaiorIgual) newChild);
            return;
        }

        if(this._explogicaMaiorigual_ == oldChild)
        {
            setExplogicaMaiorigual((PExplogicaMaiorigual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
