/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExplogicaMenorExplogicaDiff extends PExplogicaDiff
{
    private PExplogicaMenor _explogicaMenor_;

    public AExplogicaMenorExplogicaDiff()
    {
        // Constructor
    }

    public AExplogicaMenorExplogicaDiff(
        @SuppressWarnings("hiding") PExplogicaMenor _explogicaMenor_)
    {
        // Constructor
        setExplogicaMenor(_explogicaMenor_);

    }

    @Override
    public Object clone()
    {
        return new AExplogicaMenorExplogicaDiff(
            cloneNode(this._explogicaMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExplogicaMenorExplogicaDiff(this);
    }

    public PExplogicaMenor getExplogicaMenor()
    {
        return this._explogicaMenor_;
    }

    public void setExplogicaMenor(PExplogicaMenor node)
    {
        if(this._explogicaMenor_ != null)
        {
            this._explogicaMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogicaMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogicaMenor_ == child)
        {
            this._explogicaMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogicaMenor_ == oldChild)
        {
            setExplogicaMenor((PExplogicaMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
