/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExpMaiorExpExplogicaMaior extends PExplogicaMaior
{
    private PExp _exp_;
    private TMaior _maior_;
    private PExplogicaMaiorigual _explogicaMaiorigual_;

    public AExpMaiorExpExplogicaMaior()
    {
        // Constructor
    }

    public AExpMaiorExpExplogicaMaior(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PExplogicaMaiorigual _explogicaMaiorigual_)
    {
        // Constructor
        setExp(_exp_);

        setMaior(_maior_);

        setExplogicaMaiorigual(_explogicaMaiorigual_);

    }

    @Override
    public Object clone()
    {
        return new AExpMaiorExpExplogicaMaior(
            cloneNode(this._exp_),
            cloneNode(this._maior_),
            cloneNode(this._explogicaMaiorigual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMaiorExpExplogicaMaior(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PExplogicaMaiorigual getExplogicaMaiorigual()
    {
        return this._explogicaMaiorigual_;
    }

    public void setExplogicaMaiorigual(PExplogicaMaiorigual node)
    {
        if(this._explogicaMaiorigual_ != null)
        {
            this._explogicaMaiorigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaMaiorigual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._maior_)
            + toString(this._explogicaMaiorigual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._explogicaMaiorigual_ == child)
        {
            this._explogicaMaiorigual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._explogicaMaiorigual_ == oldChild)
        {
            setExplogicaMaiorigual((PExplogicaMaiorigual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
