/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExplogicaOrExplogicaAnd extends PExplogicaAnd
{
    private PExplogicaOr _explogicaOr_;

    public AExplogicaOrExplogicaAnd()
    {
        // Constructor
    }

    public AExplogicaOrExplogicaAnd(
        @SuppressWarnings("hiding") PExplogicaOr _explogicaOr_)
    {
        // Constructor
        setExplogicaOr(_explogicaOr_);

    }

    @Override
    public Object clone()
    {
        return new AExplogicaOrExplogicaAnd(
            cloneNode(this._explogicaOr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExplogicaOrExplogicaAnd(this);
    }

    public PExplogicaOr getExplogicaOr()
    {
        return this._explogicaOr_;
    }

    public void setExplogicaOr(PExplogicaOr node)
    {
        if(this._explogicaOr_ != null)
        {
            this._explogicaOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaOr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogicaOr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogicaOr_ == child)
        {
            this._explogicaOr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogicaOr_ == oldChild)
        {
            setExplogicaOr((PExplogicaOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
