/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AExpMenorExpExplogicaMenor extends PExplogicaMenor
{
    private PExp _exp_;
    private TMenor _menor_;
    private PExplogicaMenorigual _explogicaMenorigual_;

    public AExpMenorExpExplogicaMenor()
    {
        // Constructor
    }

    public AExpMenorExpExplogicaMenor(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") PExplogicaMenorigual _explogicaMenorigual_)
    {
        // Constructor
        setExp(_exp_);

        setMenor(_menor_);

        setExplogicaMenorigual(_explogicaMenorigual_);

    }

    @Override
    public Object clone()
    {
        return new AExpMenorExpExplogicaMenor(
            cloneNode(this._exp_),
            cloneNode(this._menor_),
            cloneNode(this._explogicaMenorigual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMenorExpExplogicaMenor(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public PExplogicaMenorigual getExplogicaMenorigual()
    {
        return this._explogicaMenorigual_;
    }

    public void setExplogicaMenorigual(PExplogicaMenorigual node)
    {
        if(this._explogicaMenorigual_ != null)
        {
            this._explogicaMenorigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogicaMenorigual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._menor_)
            + toString(this._explogicaMenorigual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._explogicaMenorigual_ == child)
        {
            this._explogicaMenorigual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._explogicaMenorigual_ == oldChild)
        {
            setExplogicaMenorigual((PExplogicaMenorigual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
