/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AFimCommParaFim extends PCommParaFim
{
    private PComms _comms_;

    public AFimCommParaFim()
    {
        // Constructor
    }

    public AFimCommParaFim(
        @SuppressWarnings("hiding") PComms _comms_)
    {
        // Constructor
        setComms(_comms_);

    }

    @Override
    public Object clone()
    {
        return new AFimCommParaFim(
            cloneNode(this._comms_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFimCommParaFim(this);
    }

    public PComms getComms()
    {
        return this._comms_;
    }

    public void setComms(PComms node)
    {
        if(this._comms_ != null)
        {
            this._comms_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comms_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comms_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comms_ == child)
        {
            this._comms_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comms_ == oldChild)
        {
            setComms((PComms) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
