/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AFimSimplesFimAvalie extends PFimAvalie
{
    private TFim _fim_;
    private TAvalie _avalie_;

    public AFimSimplesFimAvalie()
    {
        // Constructor
    }

    public AFimSimplesFimAvalie(
        @SuppressWarnings("hiding") TFim _fim_,
        @SuppressWarnings("hiding") TAvalie _avalie_)
    {
        // Constructor
        setFim(_fim_);

        setAvalie(_avalie_);

    }

    @Override
    public Object clone()
    {
        return new AFimSimplesFimAvalie(
            cloneNode(this._fim_),
            cloneNode(this._avalie_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFimSimplesFimAvalie(this);
    }

    public TFim getFim()
    {
        return this._fim_;
    }

    public void setFim(TFim node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    public TAvalie getAvalie()
    {
        return this._avalie_;
    }

    public void setAvalie(TAvalie node)
    {
        if(this._avalie_ != null)
        {
            this._avalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._avalie_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fim_)
            + toString(this._avalie_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        if(this._avalie_ == child)
        {
            this._avalie_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fim_ == oldChild)
        {
            setFim((TFim) newChild);
            return;
        }

        if(this._avalie_ == oldChild)
        {
            setAvalie((TAvalie) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
