/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class ANaoExplogicaExplogicaNot extends PExplogicaNot
{
    private TNao _nao_;
    private PExpLogicaInicial _expLogicaInicial_;

    public ANaoExplogicaExplogicaNot()
    {
        // Constructor
    }

    public ANaoExplogicaExplogicaNot(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") PExpLogicaInicial _expLogicaInicial_)
    {
        // Constructor
        setNao(_nao_);

        setExpLogicaInicial(_expLogicaInicial_);

    }

    @Override
    public Object clone()
    {
        return new ANaoExplogicaExplogicaNot(
            cloneNode(this._nao_),
            cloneNode(this._expLogicaInicial_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoExplogicaExplogicaNot(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public PExpLogicaInicial getExpLogicaInicial()
    {
        return this._expLogicaInicial_;
    }

    public void setExpLogicaInicial(PExpLogicaInicial node)
    {
        if(this._expLogicaInicial_ != null)
        {
            this._expLogicaInicial_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaInicial_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._expLogicaInicial_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._expLogicaInicial_ == child)
        {
            this._expLogicaInicial_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._expLogicaInicial_ == oldChild)
        {
            setExpLogicaInicial((PExpLogicaInicial) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
