/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AParentesisFator extends PFator
{
    private TAbreParentesis _abreParentesis_;
    private PExp _exp_;
    private TFechaParentesis _fechaParentesis_;

    public AParentesisFator()
    {
        // Constructor
    }

    public AParentesisFator(
        @SuppressWarnings("hiding") TAbreParentesis _abreParentesis_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TFechaParentesis _fechaParentesis_)
    {
        // Constructor
        setAbreParentesis(_abreParentesis_);

        setExp(_exp_);

        setFechaParentesis(_fechaParentesis_);

    }

    @Override
    public Object clone()
    {
        return new AParentesisFator(
            cloneNode(this._abreParentesis_),
            cloneNode(this._exp_),
            cloneNode(this._fechaParentesis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParentesisFator(this);
    }

    public TAbreParentesis getAbreParentesis()
    {
        return this._abreParentesis_;
    }

    public void setAbreParentesis(TAbreParentesis node)
    {
        if(this._abreParentesis_ != null)
        {
            this._abreParentesis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParentesis_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TFechaParentesis getFechaParentesis()
    {
        return this._fechaParentesis_;
    }

    public void setFechaParentesis(TFechaParentesis node)
    {
        if(this._fechaParentesis_ != null)
        {
            this._fechaParentesis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParentesis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abreParentesis_)
            + toString(this._exp_)
            + toString(this._fechaParentesis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abreParentesis_ == child)
        {
            this._abreParentesis_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._fechaParentesis_ == child)
        {
            this._fechaParentesis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abreParentesis_ == oldChild)
        {
            setAbreParentesis((TAbreParentesis) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._fechaParentesis_ == oldChild)
        {
            setFechaParentesis((TFechaParentesis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
