/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class ARepitaComm extends PComm
{
    private PCommRepita _commRepita_;

    public ARepitaComm()
    {
        // Constructor
    }

    public ARepitaComm(
        @SuppressWarnings("hiding") PCommRepita _commRepita_)
    {
        // Constructor
        setCommRepita(_commRepita_);

    }

    @Override
    public Object clone()
    {
        return new ARepitaComm(
            cloneNode(this._commRepita_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepitaComm(this);
    }

    public PCommRepita getCommRepita()
    {
        return this._commRepita_;
    }

    public void setCommRepita(PCommRepita node)
    {
        if(this._commRepita_ != null)
        {
            this._commRepita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commRepita_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._commRepita_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._commRepita_ == child)
        {
            this._commRepita_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._commRepita_ == oldChild)
        {
            setCommRepita((PCommRepita) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
