/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AVariosExpCommEscrevaSegundaParte extends PCommEscrevaSegundaParte
{
    private PExp _exp_;
    private TVirgula _virgula_;
    private PCommEscrevaSegundaParte _commEscrevaSegundaParte_;

    public AVariosExpCommEscrevaSegundaParte()
    {
        // Constructor
    }

    public AVariosExpCommEscrevaSegundaParte(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PCommEscrevaSegundaParte _commEscrevaSegundaParte_)
    {
        // Constructor
        setExp(_exp_);

        setVirgula(_virgula_);

        setCommEscrevaSegundaParte(_commEscrevaSegundaParte_);

    }

    @Override
    public Object clone()
    {
        return new AVariosExpCommEscrevaSegundaParte(
            cloneNode(this._exp_),
            cloneNode(this._virgula_),
            cloneNode(this._commEscrevaSegundaParte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosExpCommEscrevaSegundaParte(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PCommEscrevaSegundaParte getCommEscrevaSegundaParte()
    {
        return this._commEscrevaSegundaParte_;
    }

    public void setCommEscrevaSegundaParte(PCommEscrevaSegundaParte node)
    {
        if(this._commEscrevaSegundaParte_ != null)
        {
            this._commEscrevaSegundaParte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commEscrevaSegundaParte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._virgula_)
            + toString(this._commEscrevaSegundaParte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._commEscrevaSegundaParte_ == child)
        {
            this._commEscrevaSegundaParte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._commEscrevaSegundaParte_ == oldChild)
        {
            setCommEscrevaSegundaParte((PCommEscrevaSegundaParte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
