/* This file was generated by SableCC (http://www.sablecc.org/). */

package jah.node;

import jah.analysis.*;

@SuppressWarnings("nls")
public final class AVariosExpCommLeiaSegundaParte extends PCommLeiaSegundaParte
{
    private PExp _exp_;
    private TVirgula _virgula_;
    private PCommLeiaSegundaParte _commLeiaSegundaParte_;

    public AVariosExpCommLeiaSegundaParte()
    {
        // Constructor
    }

    public AVariosExpCommLeiaSegundaParte(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PCommLeiaSegundaParte _commLeiaSegundaParte_)
    {
        // Constructor
        setExp(_exp_);

        setVirgula(_virgula_);

        setCommLeiaSegundaParte(_commLeiaSegundaParte_);

    }

    @Override
    public Object clone()
    {
        return new AVariosExpCommLeiaSegundaParte(
            cloneNode(this._exp_),
            cloneNode(this._virgula_),
            cloneNode(this._commLeiaSegundaParte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosExpCommLeiaSegundaParte(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PCommLeiaSegundaParte getCommLeiaSegundaParte()
    {
        return this._commLeiaSegundaParte_;
    }

    public void setCommLeiaSegundaParte(PCommLeiaSegundaParte node)
    {
        if(this._commLeiaSegundaParte_ != null)
        {
            this._commLeiaSegundaParte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commLeiaSegundaParte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._virgula_)
            + toString(this._commLeiaSegundaParte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._commLeiaSegundaParte_ == child)
        {
            this._commLeiaSegundaParte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._commLeiaSegundaParte_ == oldChild)
        {
            setCommLeiaSegundaParte((PCommLeiaSegundaParte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
