/* This file was generated by SableCC (http://www.sablecc.org/). */

package linguagem.lexer;

import java.io.*;
import linguagem.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_BLOCO; break;
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_BLOCO; break;
                                case 0: state = State.COMENTARIO_BLOCO; break;
                            }
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO_BLOCO; break;
                            }
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.NORMAL; break;
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPrograma(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreParentesis(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaParentesis(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreColchetes(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaColchetes(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoEVirgula(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasSimples(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasDuplas(line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNovaLinha(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEspaco(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTab(line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumero(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBlocoAbre(line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaracteresPermitidos(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBlocoFecha(line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {93, 93, 23}, {95, 95, 24}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 26}, {101, 101, 28}, {102, 102, 29}, {103, 104, 26}, {105, 105, 30}, {106, 107, 26}, {108, 108, 31}, {109, 109, 26}, {110, 110, 32}, {111, 111, 33}, {112, 112, 34}, {113, 114, 26}, {115, 115, 35}, {116, 122, 26}, {192, 219, 36}, {224, 251, 37}, },
            {},
            {},
            {{10, 10, 38}, },
            {},
            {},
            {},
            {},
            {},
            {{47, 47, 39}, },
            {},
            {},
            {},
            {},
            {{42, 42, 40}, {47, 47, 41}, },
            {},
            {},
            {},
            {{45, 45, 42}, {61, 61, 43}, {62, 62, 44}, },
            {},
            {{61, 61, 45}, },
            {{48, 57, 46}, {65, 90, 47}, {95, 95, 48}, {97, 122, 49}, {192, 219, 50}, {224, 251, 51}, },
            {},
            {},
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 117, 49}, {118, 118, 52}, {119, 122, 49}, {192, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 97, 53}, {98, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 109, 49}, {110, 110, 54}, {111, 114, 49}, {115, 115, 55}, {116, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 104, 49}, {105, 105, 56}, {106, 122, 49}, {192, 251, -23}, },
            {{48, 109, -30}, {110, 110, 57}, {111, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 100, 49}, {101, 101, 58}, {102, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 97, 59}, {98, 251, -29}, },
            {{48, 95, -23}, {97, 116, 49}, {117, 117, 60}, {118, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 97, 61}, {98, 113, 49}, {114, 114, 62}, {115, 122, 49}, {192, 251, -23}, },
            {{48, 100, -33}, {101, 101, 63}, {102, 251, -33}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {},
            {},
            {},
            {{0, 9, 64}, {10, 10, 65}, {11, 12, 64}, {13, 13, 66}, {14, 65535, 64}, },
            {},
            {},
            {},
            {},
            {{48, 57, 46}, {65, 90, 67}, {95, 95, 68}, {97, 122, 69}, {192, 219, 70}, {224, 251, 71}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 97, 72}, {98, 251, -29}, },
            {{48, 95, -23}, {97, 114, 49}, {115, 115, 73}, {116, 251, -30}, },
            {{48, 95, -23}, {97, 112, 49}, {113, 113, 74}, {114, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 98, 49}, {99, 99, 75}, {100, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 108, 49}, {109, 109, 76}, {110, 122, 49}, {192, 251, -23}, },
            {{48, 104, -31}, {105, 105, 77}, {106, 251, -31}, },
            {{48, 104, -31}, {105, 105, 78}, {106, 251, -31}, },
            {{48, 95, -23}, {97, 110, 49}, {111, 111, 79}, {112, 122, 49}, {192, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 113, 49}, {114, 114, 80}, {115, 251, -36}, },
            {{48, 110, -61}, {111, 111, 81}, {112, 251, -61}, },
            {{48, 109, -30}, {110, 110, 82}, {111, 251, -32}, },
            {{0, 65535, -43}, },
            {},
            {{10, 10, 83}, },
            {{48, 251, -48}, },
            {{48, 251, -48}, },
            {{48, 251, -48}, },
            {{48, 251, -48}, },
            {{48, 251, -48}, },
            {{48, 95, -23}, {97, 107, 49}, {108, 108, 84}, {109, 122, 49}, {192, 251, -23}, },
            {{48, 110, -61}, {111, 111, 85}, {112, 251, -61}, },
            {{48, 116, -35}, {117, 117, 86}, {118, 251, -35}, },
            {{48, 113, -63}, {114, 114, 87}, {115, 251, -36}, },
            {{46, 46, 88}, {48, 251, -23}, },
            {{48, 98, -57}, {99, 99, 89}, {100, 251, -57}, },
            {{48, 95, -23}, {97, 97, 90}, {98, 251, -29}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 97, 91}, {98, 251, -29}, },
            {{48, 95, -23}, {97, 102, 49}, {103, 103, 92}, {104, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 97, 93}, {98, 251, -29}, },
            {},
            {{48, 104, -31}, {105, 105, 94}, {106, 251, -31}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 97, 95}, {98, 251, -29}, },
            {{48, 100, -33}, {101, 101, 96}, {102, 251, -33}, },
            {},
            {{48, 104, -31}, {105, 105, 97}, {106, 251, -31}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 113, -63}, {114, 114, 98}, {115, 251, -36}, },
            {{48, 110, -61}, {111, 111, 99}, {112, 251, -61}, },
            {{48, 100, -33}, {101, 101, 100}, {102, 251, -33}, },
            {{48, 109, -30}, {110, 110, 101}, {111, 251, -32}, },
            {{48, 117, -27}, {118, 118, 102}, {119, 251, -27}, },
            {{48, 110, -61}, {111, 111, 103}, {112, 251, -61}, },
            {{48, 95, -23}, {97, 97, 104}, {98, 251, -29}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 115, 49}, {116, 116, 105}, {117, 122, 49}, {192, 251, -23}, },
            {{48, 95, -23}, {97, 97, 106}, {98, 251, -29}, },
            {{48, 251, -23}, },
            {{48, 108, -58}, {109, 109, 107}, {110, 251, -58}, },
            {{48, 110, -61}, {111, 111, 108}, {112, 251, -61}, },
            {{48, 251, -23}, },
            {{48, 95, -23}, {97, 97, 109}, {98, 251, -29}, },
            {{48, 251, -23}, },
            {{48, 251, -23}, },
        }
        { // COMENTARIO_BLOCO
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 1}, {34, 34, 6}, {35, 38, 1}, {39, 39, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {63, 64, 1}, {65, 90, 22}, {91, 91, 23}, {92, 92, 1}, {93, 93, 24}, {94, 94, 1}, {95, 95, 25}, {96, 96, 1}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 27}, {101, 101, 29}, {102, 102, 30}, {103, 104, 27}, {105, 105, 31}, {106, 107, 27}, {108, 108, 32}, {109, 109, 27}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 114, 27}, {115, 115, 36}, {116, 122, 27}, {123, 191, 1}, {192, 219, 37}, {220, 223, 1}, {224, 251, 38}, {252, 65535, 1}, },
            {},
            {},
            {},
            {{10, 10, 39}, },
            {},
            {},
            {},
            {},
            {},
            {{47, 47, 40}, },
            {},
            {},
            {},
            {},
            {{42, 42, 41}, {47, 47, 42}, },
            {},
            {},
            {},
            {{45, 45, 43}, {61, 61, 44}, {62, 62, 45}, },
            {},
            {{61, 61, 46}, },
            {{48, 57, 47}, {65, 90, 48}, {95, 95, 49}, {97, 122, 50}, {192, 219, 51}, {224, 251, 52}, },
            {},
            {},
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 117, 50}, {118, 118, 53}, {119, 122, 50}, {192, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 97, 54}, {98, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 109, 50}, {110, 110, 55}, {111, 114, 50}, {115, 115, 56}, {116, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 104, 50}, {105, 105, 57}, {106, 122, 50}, {192, 251, -24}, },
            {{48, 109, -31}, {110, 110, 58}, {111, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 100, 50}, {101, 101, 59}, {102, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 97, 60}, {98, 251, -30}, },
            {{48, 95, -24}, {97, 116, 50}, {117, 117, 61}, {118, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 97, 62}, {98, 113, 50}, {114, 114, 63}, {115, 122, 50}, {192, 251, -24}, },
            {{48, 100, -34}, {101, 101, 64}, {102, 251, -34}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {},
            {},
            {},
            {{0, 9, 65}, {10, 10, 66}, {11, 12, 65}, {13, 13, 67}, {14, 65535, 65}, },
            {},
            {},
            {},
            {},
            {{48, 57, 47}, {65, 90, 68}, {95, 95, 69}, {97, 122, 70}, {192, 219, 71}, {224, 251, 72}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 97, 73}, {98, 251, -30}, },
            {{48, 95, -24}, {97, 114, 50}, {115, 115, 74}, {116, 251, -31}, },
            {{48, 95, -24}, {97, 112, 50}, {113, 113, 75}, {114, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 98, 50}, {99, 99, 76}, {100, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 108, 50}, {109, 109, 77}, {110, 122, 50}, {192, 251, -24}, },
            {{48, 104, -32}, {105, 105, 78}, {106, 251, -32}, },
            {{48, 104, -32}, {105, 105, 79}, {106, 251, -32}, },
            {{48, 95, -24}, {97, 110, 50}, {111, 111, 80}, {112, 122, 50}, {192, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 113, 50}, {114, 114, 81}, {115, 251, -37}, },
            {{48, 110, -62}, {111, 111, 82}, {112, 251, -62}, },
            {{48, 109, -31}, {110, 110, 83}, {111, 251, -33}, },
            {{0, 65535, -44}, },
            {},
            {{10, 10, 84}, },
            {{48, 251, -49}, },
            {{48, 251, -49}, },
            {{48, 251, -49}, },
            {{48, 251, -49}, },
            {{48, 251, -49}, },
            {{48, 95, -24}, {97, 107, 50}, {108, 108, 85}, {109, 122, 50}, {192, 251, -24}, },
            {{48, 110, -62}, {111, 111, 86}, {112, 251, -62}, },
            {{48, 116, -36}, {117, 117, 87}, {118, 251, -36}, },
            {{48, 113, -64}, {114, 114, 88}, {115, 251, -37}, },
            {{46, 46, 89}, {48, 251, -24}, },
            {{48, 98, -58}, {99, 99, 90}, {100, 251, -58}, },
            {{48, 95, -24}, {97, 97, 91}, {98, 251, -30}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 97, 92}, {98, 251, -30}, },
            {{48, 95, -24}, {97, 102, 50}, {103, 103, 93}, {104, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 97, 94}, {98, 251, -30}, },
            {},
            {{48, 104, -32}, {105, 105, 95}, {106, 251, -32}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 97, 96}, {98, 251, -30}, },
            {{48, 100, -34}, {101, 101, 97}, {102, 251, -34}, },
            {},
            {{48, 104, -32}, {105, 105, 98}, {106, 251, -32}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 113, -64}, {114, 114, 99}, {115, 251, -37}, },
            {{48, 110, -62}, {111, 111, 100}, {112, 251, -62}, },
            {{48, 100, -34}, {101, 101, 101}, {102, 251, -34}, },
            {{48, 109, -31}, {110, 110, 102}, {111, 251, -33}, },
            {{48, 117, -28}, {118, 118, 103}, {119, 251, -28}, },
            {{48, 110, -62}, {111, 111, 104}, {112, 251, -62}, },
            {{48, 95, -24}, {97, 97, 105}, {98, 251, -30}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 115, 50}, {116, 116, 106}, {117, 122, 50}, {192, 251, -24}, },
            {{48, 95, -24}, {97, 97, 107}, {98, 251, -30}, },
            {{48, 251, -24}, },
            {{48, 108, -59}, {109, 109, 108}, {110, 251, -59}, },
            {{48, 110, -62}, {111, 111, 109}, {112, 251, -62}, },
            {{48, 251, -24}, },
            {{48, 95, -24}, {97, 97, 110}, {98, 251, -30}, },
            {{48, 251, -24}, },
            {{48, 251, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 38, 36, 36, 37, 35, 34, 26, 27, 14, 12, 31, 13, 30, 15, 39, 33, 32, 17, 18, 16, 40, 28, 29, 40, 40, 40, 40, 23, 40, 40, 40, 40, 40, 40, 40, 40, 40, 36, 43, 41, -1, 25, 20, 21, 19, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 24, 40, 40, 6, -1, 44, 44, 40, 40, 40, 40, 40, 40, 40, 40, 40, 2, 40, 40, 22, 40, 40, 40, 44, 40, 8, 40, 40, 3, 40, 4, 11, 40, 40, 40, 40, 40, 40, 40, 7, 9, 40, 40, 1, 40, 40, 5, 40, 10, 0, },
        // COMENTARIO_BLOCO
        {-1, 42, 38, 36, 36, 37, 35, 34, 26, 27, 14, 12, 31, 13, 30, 15, 39, 33, 32, 17, 18, 16, 40, 28, 29, 40, 40, 40, 40, 23, 40, 40, 40, 40, 40, 40, 40, 40, 40, 36, 43, 41, -1, 25, 20, 21, 19, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 24, 40, 40, 6, -1, 44, 44, 40, 40, 40, 40, 40, 40, 40, 40, 40, 2, 40, 40, 22, 40, 40, 40, 44, 40, 8, 40, 40, 3, 40, 4, 11, 40, 40, 40, 40, 40, 40, 40, 7, 9, 40, 40, 1, 40, 40, 5, 40, 10, 0, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO_BLOCO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
