/* This file was generated by SableCC (http://www.sablecc.org/). */

package linguagem.lexer;

import java.io.*;
import linguagem.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPrograma(line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdadeiro(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoInteiro(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoReal(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoCaractere(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoBooleano(line, pos); }
    Token new33(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(text, line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new35(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(text, line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreParentesis(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaParentesis(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreColchetes(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaColchetes(line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasSimples(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasDuplas(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNovaLinha(text, line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTab(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEspaco(line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBlocoAbre(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBlocoFecha(line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {93, 93, 23}, {95, 95, 24}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 28}, {101, 101, 29}, {102, 102, 30}, {103, 104, 28}, {105, 105, 31}, {106, 107, 28}, {108, 108, 32}, {109, 109, 28}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 113, 28}, {114, 114, 36}, {115, 115, 37}, {116, 117, 28}, {118, 118, 38}, {119, 122, 28}, },
            {},
            {},
            {{10, 10, 39}, },
            {},
            {},
            {{9, 9, 40}, {32, 32, 41}, {48, 57, 42}, {65, 90, 43}, {97, 122, 44}, },
            {},
            {},
            {{47, 47, 45}, },
            {},
            {},
            {},
            {},
            {{42, 42, 46}, {47, 47, 47}, },
            {{44, 44, 48}, {48, 57, 15}, },
            {{61, 61, 49}, },
            {{10, 10, 50}, {13, 13, 51}, },
            {{61, 61, 52}, {62, 62, 53}, },
            {},
            {{61, 61, 54}, },
            {{48, 57, 55}, {65, 90, 56}, {95, 95, 57}, {97, 122, 58}, },
            {},
            {},
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 117, 58}, {118, 118, 59}, {119, 122, 58}, },
            {{48, 95, -23}, {97, 110, 58}, {111, 111, 60}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 97, 61}, {98, 110, 58}, {111, 111, 62}, {112, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 109, 58}, {110, 110, 63}, {111, 114, 58}, {115, 115, 64}, {116, 122, 58}, },
            {{48, 95, -23}, {97, 97, 65}, {98, 104, 58}, {105, 105, 66}, {106, 122, 58}, },
            {{48, 109, -31}, {110, 110, 67}, {111, 122, 58}, },
            {{48, 95, -23}, {97, 100, 58}, {101, 101, 68}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 69}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 116, 58}, {117, 117, 70}, {118, 122, 58}, },
            {{48, 95, -23}, {97, 97, 71}, {98, 113, 58}, {114, 114, 72}, {115, 122, 58}, },
            {{48, 100, -34}, {101, 101, 73}, {102, 122, 58}, },
            {{48, 100, -34}, {101, 101, 74}, {102, 122, 58}, },
            {{48, 100, -34}, {101, 101, 75}, {102, 122, 58}, },
            {},
            {{9, 32, -8}, {39, 39, 76}, {48, 122, -8}, },
            {{9, 122, -42}, },
            {{9, 122, -42}, },
            {{9, 122, -42}, },
            {{9, 122, -42}, },
            {},
            {},
            {},
            {{48, 57, 77}, },
            {},
            {},
            {{10, 10, 78}, },
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 79}, {98, 122, 58}, },
            {{48, 110, -28}, {111, 111, 80}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 113, 58}, {114, 114, 81}, {115, 115, 82}, {116, 122, 58}, },
            {{48, 109, -31}, {110, 110, 83}, {111, 122, 58}, },
            {{48, 95, -23}, {97, 112, 58}, {113, 113, 84}, {114, 122, 58}, },
            {{48, 95, -23}, {97, 98, 58}, {99, 99, 85}, {100, 122, 58}, },
            {{48, 95, -23}, {97, 107, 58}, {108, 108, 86}, {109, 122, 58}, },
            {{48, 95, -23}, {97, 108, 58}, {109, 109, 87}, {110, 122, 58}, },
            {{48, 95, -23}, {97, 104, 58}, {105, 105, 88}, {106, 115, 58}, {116, 116, 89}, {117, 122, 58}, },
            {{48, 104, -69}, {105, 105, 90}, {106, 122, 58}, },
            {{48, 110, -28}, {111, 111, 91}, {112, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 92}, {115, 122, 58}, },
            {{48, 110, -28}, {111, 111, 93}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 97, 94}, {98, 122, 58}, },
            {{48, 109, -31}, {110, 110, 95}, {111, 122, 58}, },
            {{48, 113, -63}, {114, 114, 96}, {115, 122, 58}, },
            {},
            {{48, 57, 77}, },
            {},
            {{48, 107, -67}, {108, 108, 97}, {109, 122, 58}, },
            {{48, 100, -34}, {101, 101, 98}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 99}, {98, 122, 58}, },
            {{48, 110, -28}, {111, 111, 100}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 114, 58}, {115, 115, 101}, {116, 122, 58}, },
            {{48, 116, -36}, {117, 117, 102}, {118, 122, 58}, },
            {{48, 113, -63}, {114, 114, 103}, {115, 122, 58}, },
            {{48, 114, -85}, {115, 115, 104}, {116, 122, 58}, },
            {{10, 10, 105}, {13, 13, 106}, {46, 46, 107}, {48, 122, -23}, },
            {{48, 98, -66}, {99, 99, 108}, {100, 122, 58}, },
            {{48, 100, -34}, {101, 101, 109}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 110}, {98, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 111}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 102, 58}, {103, 103, 112}, {104, 122, 58}, },
            {{48, 107, -67}, {108, 108, 113}, {109, 122, 58}, },
            {{48, 95, -23}, {97, 97, 114}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 99, 58}, {100, 100, 115}, {101, 122, 58}, },
            {{48, 104, -69}, {105, 105, 116}, {106, 122, 58}, },
            {{48, 95, -23}, {97, 97, 117}, {98, 122, 58}, },
            {{48, 98, -66}, {99, 99, 118}, {100, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 115, 58}, {116, 116, 119}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 120}, {98, 122, 58}, },
            {{48, 100, -34}, {101, 101, 121}, {102, 122, 58}, },
            {{48, 110, -28}, {111, 111, 122}, {112, 122, 58}, },
            {},
            {{10, 10, 123}, },
            {},
            {{48, 104, -69}, {105, 105, 124}, {106, 122, 58}, },
            {{48, 104, -69}, {105, 105, 125}, {106, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 126}, {115, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 110, -28}, {111, 111, 127}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 97, 128}, {98, 122, 58}, },
            {{48, 100, -34}, {101, 101, 129}, {102, 122, 58}, },
            {{48, 109, -31}, {110, 110, 130}, {111, 122, 58}, },
            {{48, 115, -103}, {116, 116, 131}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 132}, {98, 122, 58}, },
            {{48, 109, -31}, {110, 110, 133}, {111, 122, 58}, },
            {{48, 117, -27}, {118, 118, 134}, {119, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{48, 110, -28}, {111, 111, 135}, {112, 122, 58}, },
            {{48, 113, -63}, {114, 114, 136}, {115, 122, 58}, },
            {{48, 95, -23}, {97, 97, 137}, {98, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 99, -98}, {100, 100, 138}, {101, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 110, -28}, {111, 111, 139}, {112, 122, 58}, },
            {{48, 100, -34}, {101, 101, 140}, {102, 122, 58}, },
            {{48, 109, -31}, {110, 110, 141}, {111, 122, 58}, },
            {{48, 115, -103}, {116, 116, 142}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 143}, {98, 122, 58}, },
            {{10, 10, 144}, {13, 13, 145}, {48, 122, -23}, },
            {{48, 110, -28}, {111, 111, 146}, {112, 122, 58}, },
            {{48, 108, -68}, {109, 109, 147}, {110, 122, 58}, },
            {{48, 100, -34}, {101, 101, 148}, {102, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 149}, {115, 122, 58}, },
            {{48, 115, -103}, {116, 116, 150}, {117, 122, 58}, },
            {{48, 110, -28}, {111, 111, 151}, {112, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{10, 10, 152}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 153}, {98, 122, 58}, },
            {{48, 104, -69}, {105, 105, 154}, {106, 122, 58}, },
            {{48, 100, -34}, {101, 101, 155}, {102, 122, 58}, },
            {{48, 100, -34}, {101, 101, 156}, {102, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{10, 10, 157}, {13, 13, 158}, {48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 159}, {115, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {},
            {{10, 10, 160}, },
            {{48, 110, -28}, {111, 111, 161}, {112, 122, 58}, },
            {},
            {{48, 122, -23}, },
        }
        { // COMENTARIO_BLOCO
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {93, 93, 23}, {95, 95, 24}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 28}, {101, 101, 29}, {102, 102, 30}, {103, 104, 28}, {105, 105, 31}, {106, 107, 28}, {108, 108, 32}, {109, 109, 28}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 113, 28}, {114, 114, 36}, {115, 115, 37}, {116, 117, 28}, {118, 118, 38}, {119, 122, 28}, },
            {},
            {},
            {{10, 10, 39}, },
            {},
            {},
            {{9, 9, 40}, {32, 32, 41}, {48, 57, 42}, {65, 90, 43}, {97, 122, 44}, },
            {},
            {},
            {{47, 47, 45}, },
            {},
            {},
            {},
            {},
            {{42, 42, 46}, {47, 47, 47}, },
            {{44, 44, 48}, {48, 57, 15}, },
            {{61, 61, 49}, },
            {{10, 10, 50}, {13, 13, 51}, },
            {{61, 61, 52}, {62, 62, 53}, },
            {},
            {{61, 61, 54}, },
            {{48, 57, 55}, {65, 90, 56}, {95, 95, 57}, {97, 122, 58}, },
            {},
            {},
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 117, 58}, {118, 118, 59}, {119, 122, 58}, },
            {{48, 95, -23}, {97, 110, 58}, {111, 111, 60}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 97, 61}, {98, 110, 58}, {111, 111, 62}, {112, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 109, 58}, {110, 110, 63}, {111, 114, 58}, {115, 115, 64}, {116, 122, 58}, },
            {{48, 95, -23}, {97, 97, 65}, {98, 104, 58}, {105, 105, 66}, {106, 122, 58}, },
            {{48, 109, -31}, {110, 110, 67}, {111, 122, 58}, },
            {{48, 95, -23}, {97, 100, 58}, {101, 101, 68}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 69}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 116, 58}, {117, 117, 70}, {118, 122, 58}, },
            {{48, 95, -23}, {97, 97, 71}, {98, 113, 58}, {114, 114, 72}, {115, 122, 58}, },
            {{48, 100, -34}, {101, 101, 73}, {102, 122, 58}, },
            {{48, 100, -34}, {101, 101, 74}, {102, 122, 58}, },
            {{48, 100, -34}, {101, 101, 75}, {102, 122, 58}, },
            {},
            {{9, 32, -8}, {39, 39, 76}, {48, 122, -8}, },
            {{9, 122, -42}, },
            {{9, 122, -42}, },
            {{9, 122, -42}, },
            {{9, 122, -42}, },
            {},
            {},
            {},
            {{48, 57, 77}, },
            {},
            {},
            {{10, 10, 78}, },
            {},
            {},
            {},
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 79}, {98, 122, 58}, },
            {{48, 110, -28}, {111, 111, 80}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 113, 58}, {114, 114, 81}, {115, 115, 82}, {116, 122, 58}, },
            {{48, 109, -31}, {110, 110, 83}, {111, 122, 58}, },
            {{48, 95, -23}, {97, 112, 58}, {113, 113, 84}, {114, 122, 58}, },
            {{48, 95, -23}, {97, 98, 58}, {99, 99, 85}, {100, 122, 58}, },
            {{48, 95, -23}, {97, 107, 58}, {108, 108, 86}, {109, 122, 58}, },
            {{48, 95, -23}, {97, 108, 58}, {109, 109, 87}, {110, 122, 58}, },
            {{48, 95, -23}, {97, 104, 58}, {105, 105, 88}, {106, 115, 58}, {116, 116, 89}, {117, 122, 58}, },
            {{48, 104, -69}, {105, 105, 90}, {106, 122, 58}, },
            {{48, 110, -28}, {111, 111, 91}, {112, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 92}, {115, 122, 58}, },
            {{48, 110, -28}, {111, 111, 93}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 97, 94}, {98, 122, 58}, },
            {{48, 109, -31}, {110, 110, 95}, {111, 122, 58}, },
            {{48, 113, -63}, {114, 114, 96}, {115, 122, 58}, },
            {},
            {{48, 57, 77}, },
            {},
            {{48, 107, -67}, {108, 108, 97}, {109, 122, 58}, },
            {{48, 100, -34}, {101, 101, 98}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 99}, {98, 122, 58}, },
            {{48, 110, -28}, {111, 111, 100}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 114, 58}, {115, 115, 101}, {116, 122, 58}, },
            {{48, 116, -36}, {117, 117, 102}, {118, 122, 58}, },
            {{48, 113, -63}, {114, 114, 103}, {115, 122, 58}, },
            {{48, 114, -85}, {115, 115, 104}, {116, 122, 58}, },
            {{10, 10, 105}, {13, 13, 106}, {46, 46, 107}, {48, 122, -23}, },
            {{48, 98, -66}, {99, 99, 108}, {100, 122, 58}, },
            {{48, 100, -34}, {101, 101, 109}, {102, 122, 58}, },
            {{48, 95, -23}, {97, 97, 110}, {98, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 111}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 102, 58}, {103, 103, 112}, {104, 122, 58}, },
            {{48, 107, -67}, {108, 108, 113}, {109, 122, 58}, },
            {{48, 95, -23}, {97, 97, 114}, {98, 122, 58}, },
            {{48, 95, -23}, {97, 99, 58}, {100, 100, 115}, {101, 122, 58}, },
            {{48, 104, -69}, {105, 105, 116}, {106, 122, 58}, },
            {{48, 95, -23}, {97, 97, 117}, {98, 122, 58}, },
            {{48, 98, -66}, {99, 99, 118}, {100, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 115, 58}, {116, 116, 119}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 120}, {98, 122, 58}, },
            {{48, 100, -34}, {101, 101, 121}, {102, 122, 58}, },
            {{48, 110, -28}, {111, 111, 122}, {112, 122, 58}, },
            {},
            {{10, 10, 123}, },
            {},
            {{48, 104, -69}, {105, 105, 124}, {106, 122, 58}, },
            {{48, 104, -69}, {105, 105, 125}, {106, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 126}, {115, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 110, -28}, {111, 111, 127}, {112, 122, 58}, },
            {{48, 95, -23}, {97, 97, 128}, {98, 122, 58}, },
            {{48, 100, -34}, {101, 101, 129}, {102, 122, 58}, },
            {{48, 109, -31}, {110, 110, 130}, {111, 122, 58}, },
            {{48, 115, -103}, {116, 116, 131}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 132}, {98, 122, 58}, },
            {{48, 109, -31}, {110, 110, 133}, {111, 122, 58}, },
            {{48, 117, -27}, {118, 118, 134}, {119, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{48, 110, -28}, {111, 111, 135}, {112, 122, 58}, },
            {{48, 113, -63}, {114, 114, 136}, {115, 122, 58}, },
            {{48, 95, -23}, {97, 97, 137}, {98, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 99, -98}, {100, 100, 138}, {101, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 110, -28}, {111, 111, 139}, {112, 122, 58}, },
            {{48, 100, -34}, {101, 101, 140}, {102, 122, 58}, },
            {{48, 109, -31}, {110, 110, 141}, {111, 122, 58}, },
            {{48, 115, -103}, {116, 116, 142}, {117, 122, 58}, },
            {{48, 95, -23}, {97, 97, 143}, {98, 122, 58}, },
            {{10, 10, 144}, {13, 13, 145}, {48, 122, -23}, },
            {{48, 110, -28}, {111, 111, 146}, {112, 122, 58}, },
            {{48, 108, -68}, {109, 109, 147}, {110, 122, 58}, },
            {{48, 100, -34}, {101, 101, 148}, {102, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 149}, {115, 122, 58}, },
            {{48, 115, -103}, {116, 116, 150}, {117, 122, 58}, },
            {{48, 110, -28}, {111, 111, 151}, {112, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{10, 10, 152}, },
            {{48, 122, -23}, },
            {{48, 95, -23}, {97, 97, 153}, {98, 122, 58}, },
            {{48, 104, -69}, {105, 105, 154}, {106, 122, 58}, },
            {{48, 100, -34}, {101, 101, 155}, {102, 122, 58}, },
            {{48, 100, -34}, {101, 101, 156}, {102, 122, 58}, },
            {{48, 122, -23}, },
            {},
            {{10, 10, 157}, {13, 13, 158}, {48, 122, -23}, },
            {{48, 113, -63}, {114, 114, 159}, {115, 122, 58}, },
            {{48, 122, -23}, },
            {{48, 122, -23}, },
            {},
            {{10, 10, 160}, },
            {{48, 110, -28}, {111, 111, 161}, {112, 122, 58}, },
            {},
            {{48, 122, -23}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 45, 44, 44, 46, 43, 42, 37, 38, 16, 14, 33, 15, 34, 17, 47, 36, 35, 19, 20, 18, -1, 39, 40, -1, -1, -1, -1, -1, 25, -1, -1, -1, -1, -1, -1, -1, -1, -1, 44, -1, -1, -1, -1, -1, 52, 51, 50, -1, 41, 35, 35, 22, 23, 21, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 26, 49, 49, 49, 8, 49, 4, 48, 35, 49, 49, 49, 49, 49, 49, 49, 49, 2, 49, 49, 49, 24, 49, 49, 49, 49, 49, 49, 49, 49, 10, 49, 49, 49, 49, 2, 2, 3, 49, 49, 5, 13, 49, 30, 49, 49, 49, 49, 49, 49, 49, 49, 28, 2, 49, 49, 49, 9, 49, 11, 49, 49, 49, 49, 49, 1, 49, 49, 49, 32, 49, 49, 49, 6, 1, 1, 29, 49, 49, 49, 49, 12, 1, 0, 49, 31, 7, 0, 0, 49, 0, 27, },
        // COMENTARIO_BLOCO
        {-1, 45, 44, 44, 46, 43, 42, 37, 38, 16, 14, 33, 15, 34, 17, 47, 36, 35, 19, 20, 18, -1, 39, 40, -1, -1, -1, -1, -1, 25, -1, -1, -1, -1, -1, -1, -1, -1, -1, 44, -1, -1, -1, -1, -1, 52, 51, 50, -1, 41, 35, 35, 22, 23, 21, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 26, 49, 49, 49, 8, 49, 4, 48, 35, 49, 49, 49, 49, 49, 49, 49, 49, 2, 49, 49, 49, 24, 49, 49, 49, 49, 49, 49, 49, 49, 10, 49, 49, 49, 49, 2, 2, 3, 49, 49, 5, 13, 49, 30, 49, 49, 49, 49, 49, 49, 49, 49, 28, 2, 49, 49, 49, 9, 49, 11, 49, 49, 49, 49, 49, 1, 49, 49, 49, 32, 49, 49, 49, 6, 1, 1, 29, 49, 49, 49, 49, 12, 1, 0, 49, 31, 7, 0, 0, 49, 0, 27, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO_BLOCO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
