/* This file was generated by SableCC (http://www.sablecc.org/). */

package linguagem.node;

import linguagem.analysis.*;

@SuppressWarnings("nls")
public final class TCaracteresPermitidos extends Token
{
    public TCaracteresPermitidos(String text)
    {
        setText(text);
    }

    public TCaracteresPermitidos(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCaracteresPermitidos(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCaracteresPermitidos(this);
    }
}
